import cv2
img=cv2.imread("D://opencv//bbb.png") 
img1=cv2.imread("D://opencv//bbb.png")
t,rst=cv2.threshold(img,127,255,cv2.THRESH_BINARY_INV)
r,cp=cv2.threshold(img,127,255,cv2.THRESH_TRUNC)   
cv2.imshow("b",rst)
cv2.imshow("b1",img1)
cv2.imshow("b3",cp) 
cv2.waitKey()
cv2.destroyAllWindows() 
